### ISSUE TITLE
Crash on latest commit

### ISSUE THREAD

**Issue by rubenwardy** [shivajiva101/sban#6] opened 2017-11-29 20:33 UTC
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'sban' in callback on_prejoinplayer(): mods/sban/init.lua:1110: attempt to index local 'data' (a nil value)

on latest commit

**Comment by shivajiva101** [comment] 2017-11-30 02:21
hopefully fixed now, I'd implemented a limit on the query and hadn't modified the code correctly to utilise it but the crash was caused by not checking qdc returned 'false' instead of false...

**Comment by rubenwardy** [comment] 2017-11-30 19:22
Nice. I'm not going to use this on my server however until #4 is fixed.

BTW, what happens if I have both an xban and sban database? Will it merge correctly, overwrite sban stuff, or make duplicate unlinked records?

**Comment by shivajiva101** [comment] 2017-12-01 00:56
need to find a bit of time to test but the prev update should have resolved the ip not cross linking correctly

As they are in separate name spaces and sban only imports on command I can't see an issue, they would just function as before, creating unlinked records, I coded the import so it doesn't duplicate entries, based on the idea you could import from various backups including ones provided by other servers.

**Comment by shivajiva101** [comment] 2017-12-02 17:43
fixed in commit 75cfac38af4947d71ced97e64b4bf5b25f65296e

**Closed as completed by shivajiva101** 2017-12-02 17:43 UTC
Labels: bug
